package com.vlaksuga.mynextnationality

import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.ads.*
import com.vlaksuga.mynextnationality.R.*

class MainActivity : AppCompatActivity() {

    private lateinit var flagImage: ImageView
    private lateinit var resultNameView: TextView
    private lateinit var nationName: TextView
    private lateinit var nationDesc: TextView
    lateinit var mAdView : AdView
    private lateinit var mInterstitialAd: InterstitialAd

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(layout.activity_main)
        MobileAds.initialize(this) {}

        // ADMOB COVERED
        mInterstitialAd = InterstitialAd(this)
        mInterstitialAd.adUnitId = "ca-app-pub-7714576164572355/4022207856"
        mInterstitialAd.loadAd(AdRequest.Builder().build())

        mInterstitialAd.adListener = object: AdListener() {
            override fun onAdLoaded() {
                mInterstitialAd.show()
            }
        }

        // ADMOB BANNER
        mAdView = findViewById(id.adView)
        val adRequest = AdRequest.Builder().build()
        mAdView.loadAd(adRequest)


        //find Views
        flagImage = findViewById(id.flag_image)
        resultNameView = findViewById(id.result_name_text)
        nationName = findViewById(id.nation_name)
        nationDesc = findViewById(id.result_desc_text)



        // intent
        val bundle:Bundle? = intent.extras
        val resultNumber:Int? = bundle!!.getInt("calcNumber", 126) // defaultValue is Kor
        val resultName:String? = bundle.getString("userName")

        // select nation flag img
        val drawableResource = when (resultNumber) { // 0-254
            1	->	drawable.ad
            2	->	drawable.ae
            3	->	drawable.af
            4	->	drawable.ag
            5	->	drawable.ai
            6	->	drawable.al
            7	->	drawable.am
            8	->	drawable.ao
            9	->	drawable.aq
            10	->	drawable.ar
            11	->	drawable.as_
            12	->	drawable.at
            13	->	drawable.au
            14	->	drawable.aw
            15	->	drawable.ax
            16	->	drawable.az
            17	->	drawable.ba
            18	->	drawable.bb
            19	->	drawable.bd
            20	->	drawable.be
            21	->	drawable.bf
            22	->	drawable.bg
            23	->	drawable.bh
            24	->	drawable.bi
            25	->	drawable.bj
            26	->	drawable.bl
            27	->	drawable.bm
            28	->	drawable.bn
            29	->	drawable.bo
            30	->	drawable.bq
            31	->	drawable.br
            32	->	drawable.bs
            33	->	drawable.bt
            34	->	drawable.bv
            35	->	drawable.bw
            36	->	drawable.by
            37	->	drawable.bz
            38	->	drawable.ca
            39	->	drawable.cc
            40	->	drawable.cd
            41	->	drawable.cf
            42	->	drawable.cg
            43	->	drawable.ch
            44	->	drawable.ci
            45	->	drawable.ck
            46	->	drawable.cl
            47	->	drawable.cm
            48	->	drawable.cn
            49	->	drawable.co
            50	->	drawable.cr
            51	->	drawable.cu
            52	->	drawable.cv
            53	->	drawable.cw
            54	->	drawable.cx
            55	->	drawable.cy
            56	->	drawable.cz
            57	->	drawable.de
            58	->	drawable.dj
            59	->	drawable.dk
            60	->	drawable.dm
            61	->	drawable.do_
            62	->	drawable.dz
            63	->	drawable.ec
            64	->	drawable.ee
            65	->	drawable.eg
            66	->	drawable.eh
            67	->	drawable.er
            68	->	drawable.es
            69	->	drawable.et
            70	->	drawable.fi
            71	->	drawable.fj
            72	->	drawable.fk
            73	->	drawable.fm
            74	->	drawable.fo
            75	->	drawable.fr
            76	->	drawable.ga
            77	->	drawable.gb
            78	->	drawable.gb_eng
            79	->	drawable.gb_nir
            80	->	drawable.gb_sct
            81	->	drawable.gb_wls
            82	->	drawable.gd
            83	->	drawable.ge
            84	->	drawable.gf
            85	->	drawable.gg
            86	->	drawable.gh
            87	->	drawable.gi
            88	->	drawable.gl
            89	->	drawable.gm
            90	->	drawable.gn
            91	->	drawable.gp
            92	->	drawable.gq
            93	->	drawable.gr
            94	->	drawable.gs
            95	->	drawable.gt
            96	->	drawable.gu
            97	->	drawable.gw
            98	->	drawable.gy
            99	->	drawable.hk
            100	->	drawable.hm
            101	->	drawable.hn
            102	->	drawable.hr
            103	->	drawable.ht
            104	->	drawable.hu
            105	->	drawable.id
            106	->	drawable.ie
            107	->	drawable.il
            108	->	drawable.im
            109	->	drawable.in_
            110	->	drawable.io
            111	->	drawable.iq
            112	->	drawable.ir
            113	->	drawable.is_
            114	->	drawable.it
            115	->	drawable.je
            116	->	drawable.jm
            117	->	drawable.jo
            118	->	drawable.jp
            119	->	drawable.ke
            120	->	drawable.kg
            121	->	drawable.kh
            122	->	drawable.ki
            123	->	drawable.km
            124	->	drawable.kn
            125	->	drawable.kp
            126	->	drawable.kr
            127	->	drawable.kw
            128	->	drawable.ky
            129	->	drawable.kz
            130	->	drawable.la
            131	->	drawable.lb
            132	->	drawable.lc
            133	->	drawable.li
            134	->	drawable.lk
            135	->	drawable.lr
            136	->	drawable.ls
            137	->	drawable.lt
            138	->	drawable.lu
            139	->	drawable.lv
            140	->	drawable.ly
            141	->	drawable.ma
            142	->	drawable.mc
            143	->	drawable.md
            144	->	drawable.me
            145	->	drawable.mf
            146	->	drawable.mg
            147	->	drawable.mh
            148	->	drawable.mk
            149	->	drawable.ml
            150	->	drawable.mm
            151	->	drawable.mn
            152	->	drawable.mo
            153	->	drawable.mp
            154	->	drawable.mq
            155	->	drawable.mr
            156	->	drawable.ms
            157	->	drawable.mt
            158	->	drawable.mu
            159	->	drawable.mv
            160	->	drawable.mw
            161	->	drawable.mx
            162	->	drawable.my
            163	->	drawable.mz
            164	->	drawable.na
            165	->	drawable.nc
            166	->	drawable.ne
            167	->	drawable.nf
            168	->	drawable.ng
            169	->	drawable.ni
            170	->	drawable.nl
            171	->	drawable.no
            172	->	drawable.np
            173	->	drawable.nr
            174	->	drawable.nu
            175	->	drawable.nz
            176	->	drawable.om
            177	->	drawable.pa
            178	->	drawable.pe
            179	->	drawable.pf
            180	->	drawable.pg
            181	->	drawable.ph
            182	->	drawable.pk
            183	->	drawable.pl
            184	->	drawable.pm
            185	->	drawable.pn
            186	->	drawable.pr
            187	->	drawable.ps
            188	->	drawable.pt
            189	->	drawable.pw
            190	->	drawable.py
            191	->	drawable.qa
            192	->	drawable.re
            193	->	drawable.ro
            194	->	drawable.rs
            195	->	drawable.ru
            196	->	drawable.rw
            197	->	drawable.sa
            198	->	drawable.sb
            199	->	drawable.sc
            200	->	drawable.sd
            201	->	drawable.se
            202	->	drawable.sg
            203	->	drawable.sh
            204	->	drawable.si
            205	->	drawable.sj
            206	->	drawable.sk
            207	->	drawable.sl
            208	->	drawable.sm
            209	->	drawable.sn
            210	->	drawable.so
            211	->	drawable.sr
            212	->	drawable.ss
            213	->	drawable.st
            214	->	drawable.sv
            215	->	drawable.sx
            216	->	drawable.sy
            217	->	drawable.sz
            218	->	drawable.tc
            219	->	drawable.td
            220	->	drawable.tf
            221	->	drawable.tg
            222	->	drawable.th
            223	->	drawable.tj
            224	->	drawable.tk
            225	->	drawable.tl
            226	->	drawable.tm
            227	->	drawable.tn
            228	->	drawable.to
            229	->	drawable.tr
            230	->	drawable.tt
            231	->	drawable.tv
            232	->	drawable.tw
            233	->	drawable.tz
            234	->	drawable.ua
            235	->	drawable.ug
            236	->	drawable.um
            237	->	drawable.us
            238	->	drawable.uy
            239	->	drawable.uz
            240	->	drawable.va
            241	->	drawable.vc
            242	->	drawable.ve
            243	->	drawable.vg
            244	->	drawable.vi
            245	->	drawable.vn
            246	->	drawable.vu
            247	->	drawable.wf
            248	->	drawable.ws
            249	->	drawable.xk
            250	->	drawable.ye
            251	->	drawable.yt
            252	->	drawable.za
            253	->	drawable.zm
            else ->	drawable.zw
        }

        // select Nation Name
        val textResource = when (resultNumber) { // 0-254
            1	->	getString(R.string.Andorra)
            2	->	getString(R.string.United_Arab_Emirates)
            3	->	getString(R.string.Afghanistan)
            4	->	getString(R.string.Antigua_and_Barbuda)
            5	->	getString(R.string.Anguilla)
            6	->	getString(R.string.Albania)
            7	->	getString(R.string.Armenia)
            8	->	getString(R.string.Angola)
            9	->	getString(R.string.Antarctica)
            10	->	getString(R.string.Argentina)
            11	->	getString(R.string.American_Samoa)
            12	->	getString(R.string.Austria)
            13	->	getString(R.string.Australia)
            14	->	getString(R.string.Aruba)
            15	->	getString(R.string.Åland_Islands)
            16	->	getString(R.string.Azerbaijan)
            17	->	getString(R.string.Bosnia_and_Herzegovina)
            18	->	getString(R.string.Barbados)
            19	->	getString(R.string.Bangladesh)
            20	->	getString(R.string.Belgium)
            21	->	getString(R.string.Burkina_Faso)
            22	->	getString(R.string.Bulgaria)
            23	->	getString(R.string.Bahrain)
            24	->	getString(R.string.Burundi)
            25	->	getString(R.string.Benin)
            26	->	getString(R.string.Saint_Barthélemy)
            27	->	getString(R.string.Bermuda)
            28	->	getString(R.string.Brunei)
            29	->	getString(R.string.Bolivia)
            30	->	getString(R.string.Caribbean_Netherlands)
            31	->	getString(R.string.Brazil)
            32	->	getString(R.string.Bahamas)
            33	->	getString(R.string.Bhutan)
            34	->	getString(R.string.Bouvet_Island)
            35	->	getString(R.string.Botswana)
            36	->	getString(R.string.Belarus)
            37	->	getString(R.string.Belize)
            38	->	getString(R.string.Canada)
            39	->	getString(R.string.Cocos_Keeling_Islands)
            40	->	getString(R.string.DR_Congo)
            41	->	getString(R.string.Central_African_Republic)
            42	->	getString(R.string.Republic_of_the_Congo)
            43	->	getString(R.string.Switzerland)
            44	->	getString(R.string.Ivory_Coast)
            45	->	getString(R.string.Cook_Islands)
            46	->	getString(R.string.Chile)
            47	->	getString(R.string.Cameroon)
            48	->	getString(R.string.China)
            49	->	getString(R.string.Colombia)
            50	->	getString(R.string.Costa_Rica)
            51	->	getString(R.string.Cuba)
            52	->	getString(R.string.Cape_Verde)
            53	->	getString(R.string.Curaçao)
            54	->	getString(R.string.Christmas_Island)
            55	->	getString(R.string.Cyprus)
            56	->	getString(R.string.Czechia)
            57	->	getString(R.string.Germany)
            58	->	getString(R.string.Djibouti)
            59	->	getString(R.string.Denmark)
            60	->	getString(R.string.Dominica)
            61	->	getString(R.string.Dominican_Republic)
            62	->	getString(R.string.Algeria)
            63	->	getString(R.string.Ecuador)
            64	->	getString(R.string.Estonia)
            65	->	getString(R.string.Egypt)
            66	->	getString(R.string.Western_Sahara)
            67	->	getString(R.string.Eritrea)
            68	->	getString(R.string.Spain)
            69	->	getString(R.string.Ethiopia)
            70	->	getString(R.string.Finland)
            71	->	getString(R.string.Fiji)
            72	->	getString(R.string.Falkland_Islands)
            73	->	getString(R.string.Micronesia)
            74	->	getString(R.string.Faroe_Islands)
            75	->	getString(R.string.France)
            76	->	getString(R.string.Gabon)
            77	->	getString(R.string.United_Kingdom)
            78	->	getString(R.string.England)
            79	->	getString(R.string.Northern_Ireland)
            80	->	getString(R.string.Scotland)
            81	->	getString(R.string.Wales)
            82	->	getString(R.string.Grenada)
            83	->	getString(R.string.Georgia)
            84	->	getString(R.string.French_Guiana)
            85	->	getString(R.string.Guernsey)
            86	->	getString(R.string.Ghana)
            87	->	getString(R.string.Gibraltar)
            88	->	getString(R.string.Greenland)
            89	->	getString(R.string.Gambia)
            90	->	getString(R.string.Guinea)
            91	->	getString(R.string.Guadeloupe)
            92	->	getString(R.string.Equatorial_Guinea)
            93	->	getString(R.string.Greece)
            94	->	getString(R.string.South_Georgia)
            95	->	getString(R.string.Guatemala)
            96	->	getString(R.string.Guam)
            97	->	getString(R.string.Guinea_Bissau)
            98	->	getString(R.string.Guyana)
            99	->	getString(R.string.Hong_Kong)
            100	->	getString(R.string.Heard_Island_and_McDonald_Islands)
            101	->	getString(R.string.Honduras)
            102	->	getString(R.string.Croatia)
            103	->	getString(R.string.Haiti)
            104	->	getString(R.string.Hungary)
            105	->	getString(R.string.Indonesia)
            106	->	getString(R.string.Ireland)
            107	->	getString(R.string.Israel)
            108	->	getString(R.string.Isle_of_Man)
            109	->	getString(R.string.India)
            110	->	getString(R.string.British_Indian_Ocean_Territory)
            111	->	getString(R.string.Iraq)
            112	->	getString(R.string.Iran)
            113	->	getString(R.string.Iceland)
            114	->	getString(R.string.Italy)
            115	->	getString(R.string.Jersey)
            116	->	getString(R.string.Jamaica)
            117	->	getString(R.string.Jordan)
            118	->	getString(R.string.Japan)
            119	->	getString(R.string.Kenya)
            120	->	getString(R.string.Kyrgyzstan)
            121	->	getString(R.string.Cambodia)
            122	->	getString(R.string.Kiribati)
            123	->	getString(R.string.Comoros)
            124	->	getString(R.string.Saint_Kitts_and_Nevis)
            125	->	getString(R.string.North_Korea)
            126	->	getString(R.string.South_Korea)
            127	->	getString(R.string.Kuwait)
            128	->	getString(R.string.Cayman_Islands)
            129	->	getString(R.string.Kazakhstan)
            130	->	getString(R.string.Laos)
            131	->	getString(R.string.Lebanon)
            132	->	getString(R.string.Saint_Lucia)
            133	->	getString(R.string.Liechtenstein)
            134	->	getString(R.string.Sri_Lanka)
            135	->	getString(R.string.Liberia)
            136	->	getString(R.string.Lesotho)
            137	->	getString(R.string.Lithuania)
            138	->	getString(R.string.Luxembourg)
            139	->	getString(R.string.Latvia)
            140	->	getString(R.string.Libya)
            141	->	getString(R.string.Morocco)
            142	->	getString(R.string.Monaco)
            143	->	getString(R.string.Moldova)
            144	->	getString(R.string.Montenegro)
            145	->	getString(R.string.Saint_Martin)
            146	->	getString(R.string.Madagascar)
            147	->	getString(R.string.Marshall_Islands)
            148	->	getString(R.string.North_Macedonia)
            149	->	getString(R.string.Mali)
            150	->	getString(R.string.Myanmar)
            151	->	getString(R.string.Mongolia)
            152	->	getString(R.string.Macau)
            153	->	getString(R.string.Northern_Mariana_Islands)
            154	->	getString(R.string.Martinique)
            155	->	getString(R.string.Mauritania)
            156	->	getString(R.string.Montserrat)
            157	->	getString(R.string.Malta)
            158	->	getString(R.string.Mauritius)
            159	->	getString(R.string.Maldives)
            160	->	getString(R.string.Malawi)
            161	->	getString(R.string.Mexico)
            162	->	getString(R.string.Malaysia)
            163	->	getString(R.string.Mozambique)
            164	->	getString(R.string.Namibia)
            165	->	getString(R.string.New_Caledonia)
            166	->	getString(R.string.Niger)
            167	->	getString(R.string.Norfolk_Island)
            168	->	getString(R.string.Nigeria)
            169	->	getString(R.string.Nicaragua)
            170	->	getString(R.string.Netherlands)
            171	->	getString(R.string.Norway)
            172	->	getString(R.string.Nepal)
            173	->	getString(R.string.Nauru)
            174	->	getString(R.string.Niue)
            175	->	getString(R.string.New_Zealand)
            176	->	getString(R.string.Oman)
            177	->	getString(R.string.Panama)
            178	->	getString(R.string.Peru)
            179	->	getString(R.string.French_Polynesia)
            180	->	getString(R.string.Papua_New_Guinea)
            181	->	getString(R.string.Philippines)
            182	->	getString(R.string.Pakistan)
            183	->	getString(R.string.Poland)
            184	->	getString(R.string.Saint_Pierre_and_Miquelon)
            185	->	getString(R.string.Pitcairn_Islands)
            186	->	getString(R.string.Puerto_Rico)
            187	->	getString(R.string.Palestine)
            188	->	getString(R.string.Portugal)
            189	->	getString(R.string.Palau)
            190	->	getString(R.string.Paraguay)
            191	->	getString(R.string.Qatar)
            192	->	getString(R.string.Réunion)
            193	->	getString(R.string.Romania)
            194	->	getString(R.string.Serbia)
            195	->	getString(R.string.Russia)
            196	->	getString(R.string.Rwanda)
            197	->	getString(R.string.Saudi_Arabia)
            198	->	getString(R.string.Solomon_Islands)
            199	->	getString(R.string.Seychelles)
            200	->	getString(R.string.Sudan)
            201	->	getString(R.string.Sweden)
            202	->	getString(R.string.Singapore)
            203	->	getString(R.string.Saint_Helena_Ascension_and_Tristan_da_Cunha)
            204	->	getString(R.string.Slovenia)
            205	->	getString(R.string.Svalbard_and_Jan_Mayen)
            206	->	getString(R.string.Slovakia)
            207	->	getString(R.string.Sierra_Leone)
            208	->	getString(R.string.San_Marino)
            209	->	getString(R.string.Senegal)
            210	->	getString(R.string.Somalia)
            211	->	getString(R.string.Suriname)
            212	->	getString(R.string.South_Sudan)
            213	->	getString(R.string.São_Tomé_and_Príncipe)
            214	->	getString(R.string.El_Salvador)
            215	->	getString(R.string.Sint_Maarten)
            216	->	getString(R.string.Syria)
            217	->	getString(R.string.Eswatini_Swaziland)
            218	->	getString(R.string.Turks_and_Caicos_Islands)
            219	->	getString(R.string.Chad)
            220	->	getString(R.string.French_Southern_and_Antarctic_Lands)
            221	->	getString(R.string.Togo)
            222	->	getString(R.string.Thailand)
            223	->	getString(R.string.Tajikistan)
            224	->	getString(R.string.Tokelau)
            225	->	getString(R.string.Timor_Leste)
            226	->	getString(R.string.Turkmenistan)
            227	->	getString(R.string.Tunisia)
            228	->	getString(R.string.Tonga)
            229	->	getString(R.string.Turkey)
            230	->	getString(R.string.Trinidad_and_Tobago)
            231	->	getString(R.string.Tuvalu)
            232	->	getString(R.string.Taiwan)
            233	->	getString(R.string.Tanzania)
            234	->	getString(R.string.Ukraine)
            235	->	getString(R.string.Uganda)
            236	->	getString(R.string.United_States_Minor_Outlying_Islands)
            237	->	getString(R.string.United_States)
            238	->	getString(R.string.Uruguay)
            239	->	getString(R.string.Uzbekistan)
            240	->	getString(R.string.Vatican_City_Holy_See)
            241	->	getString(R.string.Saint_Vincent_and_the_Grenadines)
            242	->	getString(R.string.Venezuela)
            243	->	getString(R.string.British_Virgin_Islands)
            244	->	getString(R.string.United_States_Virgin_Islands)
            245	->	getString(R.string.Vietnam)
            246	->	getString(R.string.Vanuatu)
            247	->	getString(R.string.Wallis_and_Futuna)
            248	->	getString(R.string.Samoa)
            249	->	getString(R.string.Kosovo)
            250	->	getString(R.string.Yemen)
            251	->	getString(R.string.Mayotte)
            252	->	getString(R.string.South_Africa)
            253	->	getString(R.string.Zambia)
            else	->	getString(R.string.Zimbabwe)
        }

        // select Nation Description
        val descResource = when (resultNumber) { // 0-254
            1	->	getString(R.string.Andorra_desc)
            2	->	getString(R.string.United_Arab_Emirates_desc)
            3	->	getString(R.string.Afghanistan_desc)
            4	->	getString(R.string.Antigua_and_Barbuda_desc)
            5	->	getString(R.string.Anguilla_desc)
            6	->	getString(R.string.Albania_desc)
            7	->	getString(R.string.Armenia_desc)
            8	->	getString(R.string.Angola_desc)
            9	->	getString(R.string.Antarctica_desc)
            10	->	getString(R.string.Argentina_desc)
            11	->	getString(R.string.American_Samoa_desc)
            12	->	getString(R.string.Austria_desc)
            13	->	getString(R.string.Australia_desc)
            14	->	getString(R.string.Aruba_desc)
            15	->	getString(R.string.Åland_Islands_desc)
            16	->	getString(R.string.Azerbaijan_desc)
            17	->	getString(R.string.Bosnia_and_Herzegovina_desc)
            18	->	getString(R.string.Barbados_desc)
            19	->	getString(R.string.Bangladesh_desc)
            20	->	getString(R.string.Belgium_desc)
            21	->	getString(R.string.Burkina_faso_desc)
            22	->	getString(R.string.Bulgaria_desc)
            23	->	getString(R.string.Bahrain_desc)
            24	->	getString(R.string.Burundi_desc)
            25	->	getString(R.string.Benin_desc)
            26	->	getString(R.string.Saint_Barthélemy_desc)
            27	->	getString(R.string.Bermuda_desc)
            28	->	getString(R.string.Brunei_desc)
            29	->	getString(R.string.Bolivia_desc)
            30	->	getString(R.string.Caribbean_Netherlands_desc)
            31	->	getString(R.string.Brazil_desc)
            32	->	getString(R.string.Bahamas_desc)
            33	->	getString(R.string.Bhutan_desc)
            34	->	getString(R.string.Bouvet_Island_desc)
            35	->	getString(R.string.Botswana_desc)
            36	->	getString(R.string.Belarus_desc)
            37	->	getString(R.string.Belize_desc)
            38	->	getString(R.string.Canada_desc)
            39	->	getString(R.string.Cocos_Keeling_Islands_desc)
            40	->	getString(R.string.DR_Congo_desc)
            41	->	getString(R.string.Central_African_Republic_desc)
            42	->	getString(R.string.Republic_of_the_Congo_desc)
            43	->	getString(R.string.Switzerland_desc)
            44	->	getString(R.string.Ivory_Coast_desc)
            45	->	getString(R.string.Cook_Islands_desc)
            46	->	getString(R.string.Chile_desc)
            47	->	getString(R.string.Cameroon_desc)
            48	->	getString(R.string.China_desc)
            49	->	getString(R.string.Colombia_desc)
            50	->	getString(R.string.Costa_Rica_desc)
            51	->	getString(R.string.Cuba_desc)
            52	->	getString(R.string.Cape_Verde_desc)
            53	->	getString(R.string.Curaçao_desc)
            54	->	getString(R.string.Christmas_Island_desc)
            55	->	getString(R.string.Cyprus_desc)
            56	->	getString(R.string.Czechia_desc)
            57	->	getString(R.string.Germany_desc)
            58	->	getString(R.string.Djibouti_desc)
            59	->	getString(R.string.Denmark_desc)
            60	->	getString(R.string.Dominica_desc)
            61	->	getString(R.string.Dominican_Republic_desc)
            62	->	getString(R.string.Algeria_desc)
            63	->	getString(R.string.Ecuador_desc)
            64	->	getString(R.string.Estonia_desc)
            65	->	getString(R.string.Egypt_desc)
            66	->	getString(R.string.Western_Sahara_desc)
            67	->	getString(R.string.Eritrea_desc)
            68	->	getString(R.string.Spain_desc)
            69	->	getString(R.string.Ethiopia_desc)
            70	->	getString(R.string.Finland_desc)
            71	->	getString(R.string.Fiji_desc)
            72	->	getString(R.string.Falkland_Islands_desc)
            73	->	getString(R.string.Micronesia_desc)
            74	->	getString(R.string.Faroe_Islands_desc)
            75	->	getString(R.string.France_desc)
            76	->	getString(R.string.Gabon_desc)
            77	->	getString(R.string.United_Kingdom_desc)
            78	->	getString(R.string.England_desc)
            79	->	getString(R.string.Northern_Ireland_desc)
            80	->	getString(R.string.Scotland_desc)
            81	->	getString(R.string.Wales_desc)
            82	->	getString(R.string.Grenada_desc)
            83	->	getString(R.string.Georgia_desc)
            84	->	getString(R.string.French_Guiana_desc)
            85	->	getString(R.string.Guernsey_desc)
            86	->	getString(R.string.Ghana_desc)
            87	->	getString(R.string.Gibraltar_desc)
            88	->	getString(R.string.Greenland_desc)
            89	->	getString(R.string.Gambia_desc)
            90	->	getString(R.string.Guinea_desc)
            91	->	getString(R.string.Guadeloupe_desc)
            92	->	getString(R.string.Equatorial_Guinea_desc)
            93	->	getString(R.string.Greece_desc)
            94	->	getString(R.string.South_Georgia_desc)
            95	->	getString(R.string.Guatemala_desc)
            96	->	getString(R.string.Guam_desc)
            97	->	getString(R.string.Guinea_Bissau_desc)
            98	->	getString(R.string.Guyana_desc)
            99	->	getString(R.string.Hong_Kong_desc)
            100	->	getString(R.string.Heard_Island_and_McDonald_Islands_desc)
            101	->	getString(R.string.Honduras_desc)
            102	->	getString(R.string.Croatia_desc)
            103	->	getString(R.string.Haiti_desc)
            104	->	getString(R.string.Hungary_desc)
            105	->	getString(R.string.Indonesia_desc)
            106	->	getString(R.string.Ireland_desc)
            107	->	getString(R.string.Israel_desc)
            108	->	getString(R.string.Isle_of_Man_desc)
            109	->	getString(R.string.India_desc)
            110	->	getString(R.string.British_Indian_Ocean_Territory_desc)
            111	->	getString(R.string.Iraq_desc)
            112	->	getString(R.string.Iran_desc)
            113	->	getString(R.string.Iceland_desc)
            114	->	getString(R.string.Italy_desc)
            115	->	getString(R.string.Jersey_desc)
            116	->	getString(R.string.Jamaica_desc)
            117	->	getString(R.string.Jordan_desc)
            118	->	getString(R.string.Japan_desc)
            119	->	getString(R.string.Kenya_desc)
            120	->	getString(R.string.Kyrgyzstan_desc)
            121	->	getString(R.string.Cambodia_desc)
            122	->	getString(R.string.Kiribati_desc)
            123	->	getString(R.string.Comoros_desc)
            124	->	getString(R.string.Saint_Kitts_and_Nevis_desc)
            125	->	getString(R.string.North_Korea_desc)
            126	->	getString(R.string.South_Korea_desc)
            127	->	getString(R.string.Kuwait_desc)
            128	->	getString(R.string.Cayman_Islands_desc)
            129	->	getString(R.string.Kazakhstan_desc)
            130	->	getString(R.string.Laos_desc)
            131	->	getString(R.string.Lebanon_desc)
            132	->	getString(R.string.Saint_Lucia_desc)
            133	->	getString(R.string.Liechtenstein_desc)
            134	->	getString(R.string.Sri_Lanka_desc)
            135	->	getString(R.string.Liberia_desc)
            136	->	getString(R.string.Lesotho_desc)
            137	->	getString(R.string.Lithuania_desc)
            138	->	getString(R.string.Luxembourg_desc)
            139	->	getString(R.string.Latvia_desc)
            140	->	getString(R.string.Libya_desc)
            141	->	getString(R.string.Morocco_desc)
            142	->	getString(R.string.Monaco_desc)
            143	->	getString(R.string.Moldova_desc)
            144	->	getString(R.string.Montenegro_desc)
            145	->	getString(R.string.Saint_Martin_desc)
            146	->	getString(R.string.Madagascar_desc)
            147	->	getString(R.string.Marshall_Islands_desc)
            148	->	getString(R.string.North_Macedonia_desc)
            149	->	getString(R.string.Mali_desc)
            150	->	getString(R.string.Myanmar_desc)
            151	->	getString(R.string.Mongolia_desc)
            152	->	getString(R.string.Macau_desc)
            153	->	getString(R.string.Northern_Mariana_Islands_desc)
            154	->	getString(R.string.Martinique_desc)
            155	->	getString(R.string.Mauritania_desc)
            156	->	getString(R.string.Montserrat_desc)
            157	->	getString(R.string.Malta_desc)
            158	->	getString(R.string.Mauritius_desc)
            159	->	getString(R.string.Maldives_desc)
            160	->	getString(R.string.Malawi_desc)
            161	->	getString(R.string.Mexico_desc)
            162	->	getString(R.string.Malaysia_desc)
            163	->	getString(R.string.Mozambique_desc)
            164	->	getString(R.string.Namibia_desc)
            165	->	getString(R.string.New_Caledonia_desc)
            166	->	getString(R.string.Niger_desc)
            167	->	getString(R.string.Norfolk_Island_desc)
            168	->	getString(R.string.Nigeria_desc)
            169	->	getString(R.string.Nicaragua_desc)
            170	->	getString(R.string.Netherlands_desc)
            171	->	getString(R.string.Norway_desc)
            172	->	getString(R.string.Nepal_desc)
            173	->	getString(R.string.Nauru_desc)
            174	->	getString(R.string.Niue_desc)
            175	->	getString(R.string.New_Zealand_desc)
            176	->	getString(R.string.Oman_desc)
            177	->	getString(R.string.Panama_desc)
            178	->	getString(R.string.Peru_desc)
            179	->	getString(R.string.French_Polynesia_desc)
            180	->	getString(R.string.Papua_New_Guinea_desc)
            181	->	getString(R.string.Philippines_desc)
            182	->	getString(R.string.Pakistan_desc)
            183	->	getString(R.string.Poland_desc)
            184	->	getString(R.string.Saint_Pierre_and_Miquelon_desc)
            185	->	getString(R.string.Pitcairn_Islands_desc)
            186	->	getString(R.string.Puerto_Rico_desc)
            187	->	getString(R.string.Palestine_desc)
            188	->	getString(R.string.Portugal_desc)
            189	->	getString(R.string.Palau_desc)
            190	->	getString(R.string.Paraguay_desc)
            191	->	getString(R.string.Qatar_desc)
            192	->	getString(R.string.Réunion_desc)
            193	->	getString(R.string.Romania_desc)
            194	->	getString(R.string.Serbia_desc)
            195	->	getString(R.string.Russia_desc)
            196	->	getString(R.string.Rwanda_desc)
            197	->	getString(R.string.Saudi_Arabia_desc)
            198	->	getString(R.string.Solomon_Islands_desc)
            199	->	getString(R.string.Seychelles_desc)
            200	->	getString(R.string.Sudan_desc)
            201	->	getString(R.string.Sweden_desc)
            202	->	getString(R.string.Singapore_desc)
            203	->	getString(R.string.Saint_Helena_Ascension_and_Tristan_da_Cunha_desc)
            204	->	getString(R.string.Slovenia_desc)
            205	->	getString(R.string.Svalbard_and_Jan_Mayen_desc)
            206	->	getString(R.string.Slovakia_desc)
            207	->	getString(R.string.Sierra_Leone_desc)
            208	->	getString(R.string.San_Marino_desc)
            209	->	getString(R.string.Senegal_desc)
            210	->	getString(R.string.Somalia_desc)
            211	->	getString(R.string.Suriname_desc)
            212	->	getString(R.string.South_Sudan_desc)
            213	->	getString(R.string.São_Tomé_and_Príncipe_desc)
            214	->	getString(R.string.El_Salvador_desc)
            215	->	getString(R.string.Sint_Maarten_desc)
            216	->	getString(R.string.Syria_desc)
            217	->	getString(R.string.Eswatini_Swaziland_desc)
            218	->	getString(R.string.Turks_and_Caicos_Islands_desc)
            219	->	getString(R.string.Chad_desc)
            220	->	getString(R.string.French_Southern_and_Antarctic_Lands_desc)
            221	->	getString(R.string.Togo_desc)
            222	->	getString(R.string.Thailand_desc)
            223	->	getString(R.string.Tajikistan_desc)
            224	->	getString(R.string.Tokelau_desc)
            225	->	getString(R.string.Timor_Leste_desc)
            226	->	getString(R.string.Turkmenistan_desc)
            227	->	getString(R.string.Tunisia_desc)
            228	->	getString(R.string.Tonga_desc)
            229	->	getString(R.string.Turkey_desc)
            230	->	getString(R.string.Trinidad_and_Tobago_desc)
            231	->	getString(R.string.Tuvalu_desc)
            232	->	getString(R.string.Taiwan_desc)
            233	->	getString(R.string.Tanzania_desc)
            234	->	getString(R.string.Ukraine_desc)
            235	->	getString(R.string.Uganda_desc)
            236	->	getString(R.string.United_States_Minor_Outlying_Islands_desc)
            237	->	getString(R.string.United_States_desc)
            238	->	getString(R.string.Uruguay_desc)
            239	->	getString(R.string.Uzbekistan_desc)
            240	->	getString(R.string.Vatican_City_Holy_See_desc)
            241	->	getString(R.string.Saint_Vincent_and_the_Grenadines_desc)
            242	->	getString(R.string.Venezuela_desc)
            243	->	getString(R.string.British_Virgin_Islands_desc)
            244	->	getString(R.string.United_States_Virgin_Islands_desc)
            245	->	getString(R.string.Vietnam_desc)
            246	->	getString(R.string.Vanuatu_desc)
            247	->	getString(R.string.Wallis_and_Futuna_desc)
            248	->	getString(R.string.Samoa_desc)
            249	->	getString(R.string.Kosovo_desc)
            250	->	getString(R.string.Yemen_desc)
            251	->	getString(R.string.Mayotte_desc)
            252	->	getString(R.string.South_Africa_desc)
            253	->	getString(R.string.Zambia_desc)
            else	->	getString(R.string.Zimbabwe_desc)

        }

        // get result
        val resultUpper = resultName.toString().capitalize()
        val resultMessage = "${resultUpper}님은 다음 생에  ${textResource}에서 태어납니다!!"
        flagImage.setImageResource(drawableResource)
        resultNameView.text = resultMessage
        nationName.text = textResource
        nationDesc.text = descResource
    }

}
